### ISSUE TITLE
Execute local operation *after* remote operations have finished

### ISSUE THREAD

**Issue by NVanderEnde** [condep/ConDep#28]
Hiya,

I'd like to be able to run a local operation _after_ the remote operations, but before the ConDep process exits. Adding a custom local operation appears to execute right before the remote operations _begin_. I want to execute it as a local operation because I want it to run one time. I can do a workaround where I execute it as a remote operation and restrict its execution based on a server predicate, but it would be better if I could insert a local operation into the overall sequence at the end.

Is it possible to "bookend" the overall execution sequence like this, or is the local -> remote sequence hard-coded?

Thanks!

**Comment by torresdal** [comment]
This is a limitation/simplification in the execution sequence right now
(aka hard coded). Would an option to have it execute at the end instead of
beginning be sufficient? Then it would execute local operations in the
beginning by default, but by passing in an option you can have it execute
it in the end. Would that work for you? If so I'll look into adding this
option today.

Generally I will look into a better way of controlling the execution
sequence in the future.

On Thu, Mar 26, 2015 at 7:32 PM, Nicholas Vander Ende <
notifications@github.com> wrote:

> Hiya,
> 
> I'd like to be able to run a local operation _after_ the remote
> operations, but before the ConDep process exits. Adding a custom local
> operation appears to execute right before the remote operations _begin_.
> I want to execute it as a local operation because I want it to run one
> time. I can do a workaround where I execute it as a remote operation and
> restrict its execution based on a server predicate, but it would be better
> if I could insert a local operation into the overall sequence at the end.
> 
> Is it possible to "bookend" the overall execution sequence like this, or
> is the local -> remote sequence hard-coded?
> 
> Thanks!
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/condep/ConDep/issues/28.

## 

/Jon A.

**Comment by NVanderEnde** [comment]
Thanks for the quick reply!

I think that option would probably sort it out - I've solved my specific problem in another way (using a separate executable), so no rush. It would be great to be able to insert operations into an arbitrary part of the sequence, though!

**Comment by torresdal** [comment]
Can now confirm this is possible in v 4.0, wich we are getting very close to release. Closing this for now.
